language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
script:  ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/_mocha  && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js